// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateLinkedInProfile creates a new LinkedIn profile
 */
export function CreateLinkedInProfile(email: string, password: string): $CancellablePromise<store$0.LinkedInProfile | null> {
    return $Call.ByID(516890537, email, password).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteLinkedInProfile deletes a LinkedIn profile
 */
export function DeleteLinkedInProfile(id: number): $CancellablePromise<void> {
    return $Call.ByID(2938835488, id);
}

export function DownloadBrowser(): $CancellablePromise<void> {
    return $Call.ByID(839986558);
}

export function GetBrowserStatus(): $CancellablePromise<$models.BrowserStatus> {
    return $Call.ByID(4205620228).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLinkedInProfile retrieves a LinkedIn profile by ID
 */
export function GetLinkedInProfile(id: number): $CancellablePromise<store$0.LinkedInProfile | null> {
    return $Call.ByID(2893085521, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListLinkedInProfiles retrieves all LinkedIn profiles
 */
export function ListLinkedInProfiles(): $CancellablePromise<(store$0.LinkedInProfile | null)[]> {
    return $Call.ByID(4071004006).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SetApplying(applying: boolean): $CancellablePromise<void> {
    return $Call.ByID(2473383070, applying);
}

export function StartApplying(profileId: number): $CancellablePromise<void> {
    return $Call.ByID(2152928934, profileId);
}

export function StartBrowser(email: string, password: string): $CancellablePromise<boolean> {
    return $Call.ByID(4260629526, email, password);
}

export function StopBrowser(): $CancellablePromise<void> {
    return $Call.ByID(1627250262);
}

/**
 * UpdateLinkedInProfile updates an existing LinkedIn profile
 */
export function UpdateLinkedInProfile(id: number, update: store$0.LinkedInProfileUpdate): $CancellablePromise<store$0.LinkedInProfile | null> {
    return $Call.ByID(778799418, id, update).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = store$0.LinkedInProfile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BrowserStatus.createFrom;
const $$createType3 = $Create.Array($$createType1);
