// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BrowserStatus {
    "running": boolean;
    "applying": boolean;
    "headless": boolean;
    "downloaded": boolean;
    "version": string;

    /** Creates a new BrowserStatus instance. */
    constructor($$source: Partial<BrowserStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("applying" in $$source)) {
            this["applying"] = false;
        }
        if (!("headless" in $$source)) {
            this["headless"] = false;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserStatus($$parsedSource as Partial<BrowserStatus>);
    }
}
