// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLinkedInProfile(arg1, arg2) {
  return window['go']['app']['App']['CreateLinkedInProfile'](arg1, arg2);
}

export function DeleteLinkedInProfile(arg1) {
  return window['go']['app']['App']['DeleteLinkedInProfile'](arg1);
}

export function DownloadBrowser() {
  return window['go']['app']['App']['DownloadBrowser']();
}

export function GetBrowserStatus() {
  return window['go']['app']['App']['GetBrowserStatus']();
}

export function GetLinkedInProfile(arg1) {
  return window['go']['app']['App']['GetLinkedInProfile'](arg1);
}

export function ListLinkedInProfiles() {
  return window['go']['app']['App']['ListLinkedInProfiles']();
}

export function SetApplying(arg1) {
  return window['go']['app']['App']['SetApplying'](arg1);
}

export function StartApplying(arg1) {
  return window['go']['app']['App']['StartApplying'](arg1);
}

export function StartBrowser(arg1, arg2) {
  return window['go']['app']['App']['StartBrowser'](arg1, arg2);
}

export function StopBrowser() {
  return window['go']['app']['App']['StopBrowser']();
}

export function UpdateLinkedInProfile(arg1, arg2) {
  return window['go']['app']['App']['UpdateLinkedInProfile'](arg1, arg2);
}
