// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {app} from '../models';

export function CreateLinkedInProfile(arg1:string,arg2:string):Promise<store.LinkedInProfile>;

export function DeleteLinkedInProfile(arg1:number):Promise<void>;

export function DownloadBrowser():Promise<void>;

export function GetBrowserStatus():Promise<app.BrowserStatus>;

export function GetLinkedInProfile(arg1:number):Promise<store.LinkedInProfile>;

export function ListLinkedInProfiles():Promise<Array<store.LinkedInProfile>>;

export function SetApplying(arg1:boolean):Promise<void>;

export function StartApplying(arg1:number):Promise<void>;

export function StartBrowser(arg1:string,arg2:string):Promise<boolean>;

export function StopBrowser():Promise<void>;

export function UpdateLinkedInProfile(arg1:number,arg2:store.LinkedInProfileUpdate):Promise<store.LinkedInProfile>;
