// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * LinkedInProfile represents a user's LinkedIn profile
 */
export class LinkedInProfile {
    "id": number;
    "email": string;
    "password": string;
    "phoneNumber": string;
    "positions": string[];
    "locations": string[];
    "remoteOnly": boolean;
    "profileUrl": string;
    "yearsExperience": number;
    "userCity": string;
    "userState": string;
    "zipCode": string;
    "desiredSalary": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new LinkedInProfile instance. */
    constructor($$source: Partial<LinkedInProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("phoneNumber" in $$source)) {
            this["phoneNumber"] = "";
        }
        if (!("positions" in $$source)) {
            this["positions"] = [];
        }
        if (!("locations" in $$source)) {
            this["locations"] = [];
        }
        if (!("remoteOnly" in $$source)) {
            this["remoteOnly"] = false;
        }
        if (!("profileUrl" in $$source)) {
            this["profileUrl"] = "";
        }
        if (!("yearsExperience" in $$source)) {
            this["yearsExperience"] = 0;
        }
        if (!("userCity" in $$source)) {
            this["userCity"] = "";
        }
        if (!("userState" in $$source)) {
            this["userState"] = "";
        }
        if (!("zipCode" in $$source)) {
            this["zipCode"] = "";
        }
        if (!("desiredSalary" in $$source)) {
            this["desiredSalary"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkedInProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkedInProfile {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("positions" in $$parsedSource) {
            $$parsedSource["positions"] = $$createField4_0($$parsedSource["positions"]);
        }
        if ("locations" in $$parsedSource) {
            $$parsedSource["locations"] = $$createField5_0($$parsedSource["locations"]);
        }
        return new LinkedInProfile($$parsedSource as Partial<LinkedInProfile>);
    }
}

/**
 * LinkedInProfileUpdate contains fields that can be updated on a profile
 */
export class LinkedInProfileUpdate {
    "email": string;
    "password": string;
    "phoneNumber": string;
    "positions": string[];
    "locations": string[];
    "remoteOnly": boolean;
    "profileUrl": string;
    "yearsExperience": number;
    "userCity": string;
    "userState": string;

    /** Creates a new LinkedInProfileUpdate instance. */
    constructor($$source: Partial<LinkedInProfileUpdate> = {}) {
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("phoneNumber" in $$source)) {
            this["phoneNumber"] = "";
        }
        if (!("positions" in $$source)) {
            this["positions"] = [];
        }
        if (!("locations" in $$source)) {
            this["locations"] = [];
        }
        if (!("remoteOnly" in $$source)) {
            this["remoteOnly"] = false;
        }
        if (!("profileUrl" in $$source)) {
            this["profileUrl"] = "";
        }
        if (!("yearsExperience" in $$source)) {
            this["yearsExperience"] = 0;
        }
        if (!("userCity" in $$source)) {
            this["userCity"] = "";
        }
        if (!("userState" in $$source)) {
            this["userState"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkedInProfileUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkedInProfileUpdate {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("positions" in $$parsedSource) {
            $$parsedSource["positions"] = $$createField3_0($$parsedSource["positions"]);
        }
        if ("locations" in $$parsedSource) {
            $$parsedSource["locations"] = $$createField4_0($$parsedSource["locations"]);
        }
        return new LinkedInProfileUpdate($$parsedSource as Partial<LinkedInProfileUpdate>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
